# Generated by Django 4.2 on 2024-09-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('can_block_users', 'can block users'), ('can_view_list_of_users', 'can view list of users')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
