# Generated by Django 4.2 on 2024-09-14 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('surname', models.CharField(max_length=25, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=25, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('comment', models.TextField(max_length=255, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_datetime', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('mail_server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='заголовок сообщения')),
                ('body', models.TextField(verbose_name='текст сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='тема рассылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания рассылки')),
                ('first_message', models.DateTimeField(default=datetime.datetime(2024, 9, 14, 10, 13, 30, 86943, tzinfo=datetime.timezone.utc), verbose_name='дата и время первого письма')),
                ('last_message', models.DateTimeField(default=datetime.datetime(2024, 9, 14, 10, 13, 30, 86943, tzinfo=datetime.timezone.utc), verbose_name='дата и время последнего письма')),
                ('date_letter_was_sent', models.DateTimeField(blank=True, null=True, verbose_name='дата когда нужно отправить следующее письмо')),
                ('frequency', models.CharField(choices=[('ежедневно', 'Каждый день'), ('еженедельно', 'Раз в неделю'), ('ежемесячно', 'Раз в месяц')], verbose_name='частота отправки')),
                ('status', models.CharField(choices=[('завершена', 'Рассылка завершена'), ('создана', 'Рассылка создана'), ('запущена', 'Рассылка запущена')], verbose_name='статус рассылки')),
                ('clients', models.ManyToManyField(related_name='clients', to='sender.client', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
