# Generated by Django 4.2 on 2024-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('surname', models.CharField(max_length=25, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=25, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('comment', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='заголовок сообщения')),
                ('body', models.TextField(verbose_name='текст сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='SenderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время первого сообщения')),
                ('frequency', models.CharField(choices=[('ежедневно', 'Каждый день'), ('еженедельно', 'Раз в неделю'), ('ежемесячно', 'Раз в месяц')], verbose_name='частота отправки')),
                ('status', models.CharField(choices=[('завершена', 'Рассылка завершена'), ('создана', 'Рассылка создана'), ('запущена', 'Рассылка запущена')], verbose_name='статус рассылки')),
            ],
        ),
    ]
