# Generated by Django 4.2 on 2024-09-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('attempt_status', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('mail_server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
        ),
        migrations.AlterModelOptions(
            name='senderconfig',
            options={'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='senderconfig',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sender.client', verbose_name='клиенты'),
        ),
        migrations.AddField(
            model_name='senderconfig',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='компания'),
            preserve_default=False,
        ),
    ]
