# Generated by Django 4.2 on 2024-09-02 07:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0002_deliveryattempt_alter_senderconfig_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SenderConfig',
            new_name='Sender',
        ),
    ]
