# Generated by Django 4.2 on 2024-09-16 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sender',
            options={'permissions': [('can_switch_sending', 'can switch sending')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='sender',
            name='first_message',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 3, 56, 12, 819734, tzinfo=datetime.timezone.utc), verbose_name='дата и время первого письма'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 3, 56, 12, 819734, tzinfo=datetime.timezone.utc), verbose_name='дата и время последнего письма'),
        ),
    ]
