# Generated by Django 4.2 on 2024-09-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_rename_senderconfig_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='title',
            field=models.CharField(default='def', max_length=255, verbose_name='тема рассылки'),
            preserve_default=False,
        ),
    ]
