# Generated by Django 4.2 on 2024-09-02 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0004_sender_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massage',
            name='send',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sender.sender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(max_length=255, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='почта'),
        ),
    ]
