# Generated by Django 4.2 on 2024-09-04 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0006_alter_client_company_alter_massage_send_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='send',
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sender',
            name='message',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sender.message', verbose_name='сообщение'),
        ),
        migrations.RemoveField(
            model_name='sender',
            name='clients',
        ),
        migrations.AddField(
            model_name='sender',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to='sender.client', verbose_name='клиенты'),
        ),
    ]
