# Generated by Django 4.2 on 2024-09-07 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_alter_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='first_message',
            field=models.DateTimeField(default=datetime.date(2024, 9, 7), verbose_name='дата и время первого письма'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания рассылки'),
        ),
    ]
