# Generated by Django 4.2 on 2024-09-07 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0009_sender_first_message_alter_sender_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='first_message',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 16, 1, 16, 813122, tzinfo=datetime.timezone.utc), verbose_name='дата и время первого письма'),
        ),
    ]
