# Generated by Django 4.2 on 2024-09-08 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0010_alter_sender_first_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryattempt',
            name='attempt_status',
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sender.sender', verbose_name='рассылка для получения статуса и связи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sender',
            name='date_letter_was_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата когда нужно отправить следующее письмо'),
        ),
        migrations.AddField(
            model_name='sender',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 11, 19, 34, 615041, tzinfo=datetime.timezone.utc), verbose_name='дата и время последнего письма'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='attempt_datetime',
            field=models.DateTimeField(verbose_name='дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='first_message',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 11, 19, 34, 615041, tzinfo=datetime.timezone.utc), verbose_name='дата и время первого письма'),
        ),
    ]
