# Generated by Django 4.2 on 2024-09-11 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0013_alter_sender_first_message_alter_sender_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='first_message',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 14, 44, 36, 214481, tzinfo=datetime.timezone.utc), verbose_name='дата и время первого письма'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 14, 44, 36, 214481, tzinfo=datetime.timezone.utc), verbose_name='дата и время последнего письма'),
        ),
    ]
