# Generated by Django 4.2 on 2024-09-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='заголовок')),
                ('image', models.ImageField(upload_to='media/')),
                ('content', models.TextField(verbose_name='содержимое статьи')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания статьи')),
                ('viewed', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись в блоге',
                'verbose_name_plural': 'записи в блоге',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
