# Generated by Django 5.0.6 on 2024-08-10 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-z\\-]*$', 'Только безопасные символы')], verbose_name='slug')),
                ('content', models.TextField(verbose_name='содержимое статьи')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания статьи')),
                ('is_published', models.BooleanField(verbose_name='признак публикации')),
                ('viewed', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись в блоге',
                'verbose_name_plural': 'записи в блоге',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
