# Generated by Django 4.2 on 2024-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
    ]
